### ISSUE TITLE
OpenAPI/SwaggerUI

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-quarkus#6]
Simply integrate the Quarkus built-in OpenAPI/SwaggerUI into JHipster web pages.

**Comment by avdev4j** [comment]
@danielpetisme do you think the pr from @inngvar is enough? If yes, @inngvar don't forget to claim the bounty.

**Comment by inngvar** [comment]
@jdubois claiming bounty )

**Comment by jdubois** [comment]
@inngvar don't forget to do it on OpenCollective too, that's where the money comes from. If you need help doing it, just ask!

**Comment by inngvar** [comment]
@jdubois some help will be helpfull, Do I understand correctly that I need to create an invoice here https://opencollective.com/generator-jhipster/expenses/new, and specify the issue link in the expense title?

**Comment by jdubois** [comment]
@inngvar yes you need to create an invoice (there should be an example, otherwise you can have a look at https://www.jhipster.tech/bug-bounties/ ). You should also link the issue title so I'm sure it is you (in case someone smart tries to steal the bounty from you - it never happened but we are cautious).
